In [1]:
a = ' Levenshtein'
b = ' Livinshten'  # we include empty space at start of each word

# the Levenshtein distance is 3: in strig b we need to change "i" thrice to get it to match string a

In [9]:
import numpy as np
# initialize empty zero array
lev = np.zeros((len(a), len(b)))
lev

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# Wagner- Fischer algo

for i in range(len(a)):
    for j in range(len(b)):
        # if i or j are 0
        if min([i, j]) == 0:
            # we assign matrix value at position i, j = max(i, j)
            lev[i, j] = max([i, j])
        else:
            # calculate our three possible operations
            x = lev[i-1, j]  # deletion
            y = lev[i, j-1]  # insertion
            z = lev[i-1, j-1]  # substitution
            # take the minimum (eg best path/operation)
            lev[i, j] = min([x, y, z])
            # and if our two current characters don't match, add 1
            if a[i] != b[j]:
                # if we have a match, don't add 1
                lev[i, j] += 1
print(lev)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  1.  1.  2.  3.  4.  5.  6.  7.  7.  8.]
 [ 3.  2.  2.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 4.  3.  3.  2.  2.  3.  4.  5.  6.  6.  7.]
 [ 5.  4.  4.  3.  3.  2.  3.  4.  5.  6.  6.]
 [ 6.  5.  5.  4.  4.  3.  2.  3.  4.  5.  6.]
 [ 7.  6.  6.  5.  5.  4.  3.  2.  3.  4.  5.]
 [ 8.  7.  7.  6.  6.  5.  4.  3.  2.  3.  4.]
 [ 9.  8.  8.  7.  7.  6.  5.  4.  3.  2.  3.]
 [10.  9.  8.  8.  7.  7.  6.  5.  4.  3.  3.]
 [11. 10.  9.  9.  8.  7.  7.  6.  5.  4.  3.]]


In [14]:
# The optimal path through our matrix — in position [-1, -1] at the bottom-right we have the Levenshtein distance between our two strings.
lev[-1, -1]

3.0